name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1-dev.2

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  easy_theme_extension: ^0.0.1-dev.7
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.11.1
  easy_theme_extension_builder: ^0.0.1-dev.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
