name: easy_theme_extension_workspace

environment:
  sdk: ^3.11.0

workspace: 
  - packages/*
  - packages/*/example

dev_dependencies:
  melos: ^7.4.0

dependencies:
  very_good_analysis: ^10.2.0

melos:
  sdkPath: .fvm/flutter_sdk
