name: easy_theme_extension_builder
description: Builder package for easy_theme_extension.
version: 0.0.1-dev.3

repository: https://github.com/albinpk/easy_theme_extension
issue_tracker: https://github.com/albinpk/easy_theme_extension/issues

environment:
  sdk: ^3.11.0
  
resolution: workspace

dependencies:
  analyzer: ^10.0.1
  build: ^4.0.4
  built_collection: ^5.1.1
  code_builder: ^4.11.1
  dart_style: ^3.1.5
  easy_theme_extension: ^0.0.1-dev.3
  source_gen: ^4.2.0

dev_dependencies:
  test: ^1.25.6
  

