name: easy_theme_extension
description: A starting point for Dart libraries or applications.
version: 0.0.1-dev.2

repository: https://github.com/albinpk/easy_theme_extension
issue_tracker: https://github.com/albinpk/easy_theme_extension/issues

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  meta: ^1.17.0

dev_dependencies:
  test: ^1.25.6
